# Generated by Django 3.1.5 on 2021-10-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_bairro_cidade_estado_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairro'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidade'},
        ),
        migrations.AlterModelOptions(
            name='duvida',
            options={'verbose_name': 'Dúvida frequente', 'verbose_name_plural': 'Dúvidas frequentes'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.pais', verbose_name='Pais'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('dataNascimento', models.DateField(verbose_name='dataNascimento')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('cpf', models.CharField(max_length=100, verbose_name='cpf')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereco')),
                ('pontoReferencia', models.CharField(blank=True, max_length=100, verbose_name='pontoReferencia')),
                ('numeroPets', models.IntegerField(default=0, verbose_name='numeroPets')),
                ('termosCondicoes', models.BooleanField(verbose_name='termosCondicoes')),
                ('politicaPrivacidade', models.BooleanField(verbose_name='termosCondicoes')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.bairro', verbose_name='Bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.cidade', verbose_name='Cidade')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.estado', verbose_name='Estado')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
