# Generated by Django 3.1.5 on 2021-10-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20211028_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvida',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=100, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numeroPets',
            field=models.IntegerField(default=0, verbose_name='Número de Pets'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='politicaPrivacidade',
            field=models.BooleanField(verbose_name='Política de Privacidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pontoReferencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ponto de referência'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='termosCondicoes',
            field=models.BooleanField(verbose_name='Termos e Condições'),
        ),
    ]
