# Generated by Django 3.1.5 on 2021-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20211028_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('duracaoServico', models.FloatField(verbose_name='Tempo de serviço')),
                ('instrucoes', models.CharField(max_length=100, verbose_name='Instruções')),
                ('quemRecebera', models.CharField(max_length=100, verbose_name='Quem receberá')),
                ('incluirProduto', models.BooleanField(verbose_name='Incluir produtos')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamento',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('nota', models.IntegerField(verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairro',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('resposta', models.TextField(verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numeroPets',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apelido',
            field=models.CharField(max_length=100, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='Pets'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=255, null=True, verbose_name='Sobrenome'),
        ),
    ]
