# Generated by Django 3.1.5 on 2021-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20211108_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
